services:
  dotnet-mysql:
    image: mysql:8.0
    working_dir: /application
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dotnet_todos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - todos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-ppassword"]
      interval: 2s
      retries: 3
      timeout: 5s

networks:
  todos:
    driver: bridge

volumes:
  mysql-data: